#!/bin/bash

# Configuration
PLUGIN_NAME="caelestia-nvim"
# Fallback repo if we can't detect it from git
DEFAULT_REPO="atdma/caelestia-nvim"
NVIM_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/nvim"
PLUGINS_DIR="$NVIM_CONFIG_DIR/lua/plugins"
TARGET_FILE="$PLUGINS_DIR/caelestia.lua"

echo "Installing $PLUGIN_NAME for LazyVim..."

# 1. Try to detect the actual git remote URL
if git remote get-url origin >/dev/null 2>&1; then
    # Extracts 'username/repo' from various git URL formats
    PLUGIN_REPO=$(git remote get-url origin | sed -E 's/.*[:\/]([^\/]+\/[^\/]+)(\.git)?$/\1/')
else
    PLUGIN_REPO="$DEFAULT_REPO"
fi

# 2. Check if nvim config exists
if [ ! -d "$NVIM_CONFIG_DIR" ]; then
    echo "Error: Neovim configuration directory not found at $NVIM_CONFIG_DIR"
    exit 1
fi

# 3. Check for lazy.nvim
if [ ! -f "$NVIM_CONFIG_DIR/lazy-lock.json" ] && [ ! -f "$NVIM_CONFIG_DIR/lua/config/lazy.lua" ]; then
    echo "Warning: Could not confirm lazy.nvim is being used in $NVIM_CONFIG_DIR"
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# 4. Create plugins directory if it doesn't exist
mkdir -p "$PLUGINS_DIR"

# 5. Determine if we should use a local path (for developers) or remote (for users)
# We check if we are currently inside the plugin directory
if [ -f "lua/caelestia/init.lua" ]; then
    CURRENT_DIR=$(pwd)
    echo "Local version detected at $CURRENT_DIR"
    read -p "Install as local plugin for development? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        PLUGIN_ENTRY="{ \"caelestia\", dir = \"$CURRENT_DIR\", priority = 1000, lazy = false, opts = {} }"
    else
        PLUGIN_ENTRY="{ \"$PLUGIN_REPO\", priority = 1000, lazy = false, opts = {} }"
    fi
else
    PLUGIN_ENTRY="{ \"$PLUGIN_REPO\", priority = 1000, lazy = false, opts = {} }"
fi

# 6. Create/Overwrite the spec file
# We use double brackets for the lua table to avoid escaping issues with single quotes
cat > "$TARGET_FILE" <<EOF
-- Automatically generated by caelestia-nvim install script
return {
  -- Add the caelestia-nvim plugin
  $PLUGIN_ENTRY,

  -- Configure LazyVim to use caelestia as the colorscheme
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "caelestia",
    },
  },
}
EOF

echo "Success: Created $TARGET_FILE"
echo "Restart Neovim to load the theme."
